site_name: Fast Connect Credential Insertion API  for Citrix Workspace app 1808 for Linux
site_description: Fast Connect Credential Insertion API  for Citrix Workspace app 1808 for Linux
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True
pages:

- Home: index.md
- Setting up your environment: setting-up-your-environment.md
- API functions: api-functions.md
- API examples: api-examples.md
- Credential comparison rules: credential-comparison-rules.md
